phrase = 'string in a variable'
print(phrase)
print('\n' + phrase + ' ' + 'and concatenated string')
print(phrase.capitalize())
print(phrase.upper())
print(phrase.isupper())
print(phrase.islower())
print(len(phrase))
print(phrase[2])
print(phrase.index("s"))
print(phrase)
print(phrase.replace('variable', 'variable_replaced').capitalize())